package org.models;

import static org.models.Behaviour.*;

import static org.models.Role.DAMAGE;
import static org.models.Role.MAGE;
import static org.models.Role.SOLDIER;
import static org.models.Role.SUPPORT;
import static org.models.Role.TANK;
import static org.models.Role.JUNGLE;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public enum Hero {

	AAMON(JUNGLE, Arrays.asList(MAGIC_DAMAGE, INVISIBILITY, REGENERATION, CROWD_CONTROL)),
	AKAI(TANK, Arrays.asList(SHIELD, KNOCK_BACK, SKILL_SUPPRESSION, SPLASH_DAMAGE)),
	ALDOUS(SOLDIER, Arrays.asList(HIGH_MOBILITY, SHIELD,EXPLOSION, CONTROL_IMMUNITY)),
	ALICE(MAGE, Arrays.asList(REGENERATION, DASH)),
	ALPHA(SOLDIER, Arrays.asList(REAL_DAMAGE)),
	ALUCARD(DAMAGE, Arrays.asList(REGENERATION, DASH, ARMOR_BREAKER)),
	ANGELA(SUPPORT, Arrays.asList(REGENERATION, SHIELD, CROWD_CONTROL)),
	ARGUS(SOLDIER, Arrays.asList(INVULNERABILITY, DASH)),
	ATLAS(TANK, Arrays.asList(CROWD_CONTROL, ENDURANCE, SKILL_SUPPRESSION, PULL)),
	AULUS(SOLDIER, Arrays.asList(HIGH_MOBILITY, REGENERATION, SPLASH_DAMAGE)),
	AURORA(MAGE, Arrays.asList(CROWD_CONTROL, EXPLOSION)),
	BADANG(SOLDIER, Arrays.asList(SPLASH_DAMAGE, ENCAGE, SKILL_SUPPRESSION)),
	BALMOND(SOLDIER, Arrays.asList(REAL_DAMAGE,REGENERATION, SPLASH_DAMAGE, DASH)),
	BANE(JUNGLE, Arrays.asList(REGENERATION,CROWD_CONTROL, SPLASH_DAMAGE, PUSH)),
	BARATS(TANK, Arrays.asList(ENDURANCE, ENCAGE, SKILL_SUPPRESSION)),
	BAXIA(SOLDIER, Arrays.asList(HIGH_MOBILITY, REGENERATION_REDUCTION)),
	BEATRIX(DAMAGE, Arrays.asList(LONG_RANGE, SPLASH_DAMAGE)),
	BELERICK(TANK, Arrays.asList(REFLECTION, HP_POOL, CROWD_CONTROL)),
	BENEDETA(DAMAGE, Arrays.asList(HIGH_MOBILITY, INVULNERABILITY, SPLASH_DAMAGE)),
	BRODY(DAMAGE, Arrays.asList(LONG_RANGE, CROWD_CONTROL)),
	BRUNO(DAMAGE, Arrays.asList(REAP)),
	CARMILLA(TANK, Arrays.asList(ENDURANCE, CROWD_CONTROL)),
	CECILION(MAGE, Arrays.asList(CROWD_CONTROL)),
	CHANGE(MAGE, Arrays.asList(LONG_RANGE)),
	CHOU(DAMAGE, Arrays.asList(CONTROL_IMMUNITY, DASH, CROWD_CONTROL, SHIELD)),
	CLAUDE(DAMAGE, Arrays.asList(HIGH_MOBILITY, REAP)),
	CLINT(JUNGLE, Arrays.asList(ARMOR_BREAKER,SPLASH_DAMAGE)),
	CYCLOPS(MAGE, Arrays.asList(CROWD_CONTROL, HIGH_MOBILITY,ENCAGE)),
	DIGGIE(SUPPORT, Arrays.asList(CONTROL_IMMUNITY, ENCAGE)),
	DYRROTH(DAMAGE, Arrays.asList(REGENERATION, EXPLOSION)),
	EDITH(SOLDIER,Arrays.asList(ENDURANCE, CROWD_CONTROL)),
	ESMERALDA(JUNGLE, Arrays.asList(SHIELD_STEALING, REGENERATION)),
	ESTES(SUPPORT, Arrays.asList(REGENERATION)),
	EUDORA(MAGE, Arrays.asList(SKILL_SUPPRESSION,EXPLOSION)),
	FANNY(DAMAGE, Arrays.asList(HIGH_MOBILITY, REGENERATION)),
	FARAMIS(SUPPORT, Arrays.asList(RESSURRECTION, SPLASH_DAMAGE)),
	FREDERIN(TANK, Arrays.asList(REGENERATION, ENDURANCE, CROWD_CONTROL, REFLECTION)),
	FLORYN(SUPPORT, Arrays.asList(SHIELD, REGENERATION)),
	FRANCO(TANK, Arrays.asList(SKILL_SUPPRESSION, REGENERATION, PULL)),
	FREYA(SOLDIER, Arrays.asList(ENDURANCE, SHIELD)),
	GATOTKACA(TANK, Arrays.asList(ENDURANCE, CROWD_CONTROL)),
	GLOO(TANK, Arrays.asList(ENDURANCE, SKILL_SUPPRESSION)),
	GORD(MAGE, Arrays.asList(REAL_DAMAGE)),
	GRANGER(DAMAGE, Arrays.asList(HIGH_MOBILITY)),
	GROCK(TANK, Arrays.asList(CONTROL_IMMUNITY, ENCAGE, ENDURANCE)),
	GUINEVERE(JUNGLE, Arrays.asList(SKILL_SUPPRESSION, DASH, REGENERATION)),
	GUSION(JUNGLE, Arrays.asList(HIGH_MOBILITY, EXPLOSION)),
	HANABI(DAMAGE, Arrays.asList(SPLASH_DAMAGE)),
	HANZO(JUNGLE, Arrays.asList(HIGH_MOBILITY, INVULNERABILITY)),
	HARITH(MAGE, Arrays.asList(CROWD_CONTROL, HIGH_MOBILITY)),
	HARLEY(JUNGLE, Arrays.asList(HIGH_MOBILITY)),
	HAYABUSA(DAMAGE, Arrays.asList(HIGH_MOBILITY, INVULNERABILITY, SPLASH_DAMAGE)),
	HELCURT(JUNGLE, Arrays.asList(SKILL_SUPPRESSION, INVISIBILITY)),
	HILDA(SOLDIER, Arrays.asList(SHIELD, REGENERATION)),
	HYLOS(SUPPORT, Arrays.asList(HP_POOL, CROWD_CONTROL)),
	IRITHEL(DAMAGE, Arrays.asList(REAP)),
	JAWHEAD(SOLDIER, Arrays.asList(ENDURANCE, SHIELD, HIGH_MOBILITY)),
	JOHNSON(TANK, Arrays.asList(HIGH_MOBILITY, CROWD_CONTROL)),
	KADITA(MAGE, Arrays.asList(INVULNERABILITY, EXPLOSION)),
	KAGURA(MAGE, Arrays.asList(CONTROL_IMMUNITY, SPLASH_DAMAGE)),
	KAJA(MAGE, Arrays.asList(SKILL_SUPPRESSION)),
	KARINA(JUNGLE, Arrays.asList(REAL_DAMAGE, INVULNERABILITY)),
	KARRIE(DAMAGE, Arrays.asList(REAL_DAMAGE, HP_BASED_DAMAGE)),
	KHALEED(SOLDIER, Arrays.asList(ENDURANCE, REGENERATION)),
	KHUFRA(JUNGLE, Arrays.asList(HIGH_MOBILITY, ENCAGE)),
	KIMMY(JUNGLE, Arrays.asList(HIGH_MOBILITY, REAP, LONG_RANGE)),
	JULIAN(JUNGLE, Arrays.asList(REGENERATION)),
	LANCELOT(DAMAGE, Arrays.asList(INVULNERABILITY, DASH, SPLASH_DAMAGE)),
	LAPULAPU(SOLDIER, Arrays.asList(REGENERATION)),
	LAYLA(DAMAGE, Arrays.asList(LONG_RANGE)),
	LEOMORD(DAMAGE, Arrays.asList(REGENERATION, ENDURANCE)),
	LESLEY(DAMAGE, Arrays.asList(LONG_RANGE,HIGH_MOBILITY,KNOCK_BACK)),
	LING(DAMAGE, Arrays.asList(INVISIBILITY, HIGH_MOBILITY)),
	LOLITA(SUPPORT, Arrays.asList(DASH, SHIELD, CROWD_CONTROL)),
	LUNOX(MAGE, Arrays.asList(ARMOR_BREAKER, REAP, CONTROL_IMMUNITY)),
	LOUYI(SUPPORT, Arrays.asList(CROWD_CONTROL, SPLASH_DAMAGE,HIGH_MOBILITY)),
	LYLIA(MAGE, Arrays.asList(CROWD_CONTROL, REGENERATION)),
	MARTIS(DAMAGE, Arrays.asList(CONTROL_IMMUNITY, REGENERATION)),
	MASHA(DAMAGE, Arrays.asList(HIGH_MOBILITY, SHIELD)),
	MATHILDA(SUPPORT, Arrays.asList(HIGH_MOBILITY)),
	MELISSA(JUNGLE, Arrays.asList(CROWD_CONTROL, CONTROL_IMMUNITY)),
	MINOTAUR(SUPPORT, Arrays.asList(REGENERATION, SKILL_SUPPRESSION)),
	MINSITTHAR(SUPPORT, Arrays.asList(DASH_SUPPRESSION,SHIELD, PULL)),
	MYA(DAMAGE, Arrays.asList(REAP, CONTROL_IMMUNITY, SPLASH_DAMAGE)),
	MOSKOV(DAMAGE, Arrays.asList(REAP, CROWD_CONTROL)),
	NANA(MAGE, Arrays.asList(RESSURRECTION, CROWD_CONTROL, SKILL_SUPPRESSION)),
	NATALIA(DAMAGE, Arrays.asList(HIGH_MOBILITY, INVISIBILITY)),
	NATAN(JUNGLE, Arrays.asList(KNOCK_BACK, LONG_RANGE)),
	ODETTE(MAGE, Arrays.asList(SPLASH_DAMAGE)),
	PAQUITO(SOLDIER, Arrays.asList(INVULNERABILITY, HIGH_MOBILITY, SKILL_SUPPRESSION)),
	PHARSA(MAGE, Arrays.asList(HIGH_MOBILITY, LONG_RANGE)),
	PHOVEUS(SOLDIER, Arrays.asList(HIGH_MOBILITY, ENDURANCE, SKILL_SUPPRESSION)),
	POPOL(SOLDIER, Arrays.asList(SUMMON)),
	RAFAELA(SUPPORT, Arrays.asList(REGENERATION, CROWD_CONTROL)),
	ROGER(SOLDIER, Arrays.asList(HIGH_MOBILITY, REAP, REGENERATION)),
	RUBY(TANK, Arrays.asList(REGENERATION, CROWD_CONTROL, SPLASH_DAMAGE)),
	SABER(DAMAGE, Arrays.asList(EXPLOSION, SKILL_SUPPRESSION)),
	SELENA(MAGE, Arrays.asList(LONG_RANGE, CROWD_CONTROL)),
	SILVANNA(JUNGLE, Arrays.asList(SHIELD, ENCAGE)),
	SUN(SOLDIER, Arrays.asList(SUMMON, REAP)),
	TERIZLA(SOLDIER, Arrays.asList(REGENERATION)),
	THAMUZ(SOLDIER, Arrays.asList(REGENERATION, REAL_DAMAGE)),
	TIGREAL(TANK, Arrays.asList(ENDURANCE, KNOCK_BACK, CROWD_CONTROL)),
	URANUS(TANK, Arrays.asList(REGENERATION, SHIELD)),
	VALE(MAGE, Arrays.asList(HIGH_MOBILITY, CROWD_CONTROL)),
	VALIR(MAGE, Arrays.asList(CROWD_CONTROL, SKILL_SUPPRESSION, PUSH)),
	VALENTINA(MAGE, Arrays.asList(LONG_RANGE,CROWD_CONTROL)),
	VEXANA(MAGE, Arrays.asList(SUMMON)),
	WANWAN(DAMAGE, Arrays.asList(CONTROL_IMMUNITY, INVULNERABILITY)),
	XBORG(SOLDIER, Arrays.asList(REAL_DAMAGE, SHIELD)),
	YISUNSHIN(DAMAGE, Arrays.asList(LONG_RANGE, INVULNERABILITY)),
	YUZHONG(SOLDIER, Arrays.asList(REGENERATION, HIGH_MOBILITY)),
	YVE(MAGE, Arrays.asList(LONG_RANGE)),
	ZHASK(SOLDIER, Arrays.asList(SUMMON, CROWD_CONTROL)),
	ZILONG(DAMAGE, Arrays.asList(HIGH_MOBILITY, REAP, CONTROL_IMMUNITY));

	private Role role;
	private List<Behaviour> strengths;
	private List<Behaviour> weaknesses = new ArrayList<Behaviour>();

	Hero(Role role, List<Behaviour> strengths) {
		this.role = role;
		this.strengths = strengths;
	}

	private static Map<String, Hero> heroesNameMap = new HashMap<String, Hero>();

	static {
		Hero[] values = Hero.values();
		int ammountValues = values.length;

		if (heroesNameMap.isEmpty()) {
			for (int i = 0; i < ammountValues; i++) {
				heroesNameMap.put(String.valueOf(values[i]), values[i]);
			}
		}

	}

	public static Map<String, Hero> getHeroesNameMap() {
		return heroesNameMap;
	}

	public Role getRole() {
		return role;
	}

	public List<Behaviour> getWeaknesses() {
		return weaknesses;
	}

	public List<Behaviour> getStrengths() {
		return strengths;
	}

}