package org.models;

import static org.models.Behaviour.ARMOR_BREAKER_REAL_DAMAGE;
import static org.models.Behaviour.CONTROL_IMMUNITY;
import static org.models.Behaviour.DASH;
import static org.models.Behaviour.DASH_SUPPRESSION;
import static org.models.Behaviour.ENCAGE;
import static org.models.Behaviour.ENDURANCE;
import static org.models.Behaviour.EXPLOSION;
import static org.models.Behaviour.HIGH_MOBILITY;
import static org.models.Behaviour.HP_BASED_DAMAGE;
import static org.models.Behaviour.HP_POOL;
import static org.models.Behaviour.INVISIBILITY;
import static org.models.Behaviour.INVULNERABILITY;
import static org.models.Behaviour.KNOCK_BACK;
import static org.models.Behaviour.LONG_RANGE;
import static org.models.Behaviour.MAGIC_DAMAGE;
import static org.models.Behaviour.PULL;
import static org.models.Behaviour.REAP;
import static org.models.Behaviour.REFLECTION;
import static org.models.Behaviour.REGENERATION;
import static org.models.Behaviour.REGENERATION_REDUCTION;
import static org.models.Behaviour.RESSURRECTION;
import static org.models.Behaviour.SHIELD;
import static org.models.Behaviour.SHIELD_STEALING;
import static org.models.Behaviour.SKILL_SUPPRESSION;
import static org.models.Behaviour.SLOW;
import static org.models.Behaviour.SPLASH_DAMAGE;
import static org.models.Behaviour.SUMMON;
import static org.models.Behaviour.STUN;
import static org.models.Role.DAMAGE;
import static org.models.Role.JUNGLE;
import static org.models.Role.MAGE;
import static org.models.Role.SOLDIER;
import static org.models.Role.SUPPORT;
import static org.models.Role.TANK;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public enum Hero {

	AAMON(JUNGLE, Arrays.asList(MAGIC_DAMAGE, INVISIBILITY, REGENERATION, SLOW)),
	AKAI(TANK, Arrays.asList(SHIELD, KNOCK_BACK, SKILL_SUPPRESSION, SPLASH_DAMAGE)),
	ALDOUS(SOLDIER, Arrays.asList(HIGH_MOBILITY, SHIELD,EXPLOSION, CONTROL_IMMUNITY)),
	ALICE(MAGE, Arrays.asList(REGENERATION, DASH, LONG_RANGE, HIGH_MOBILITY)),
	ALPHA(SOLDIER, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE, SKILL_SUPPRESSION, SPLASH_DAMAGE)),
	ALUCARD(DAMAGE, Arrays.asList(REGENERATION, DASH, ARMOR_BREAKER_REAL_DAMAGE)),
	ANGELA(SUPPORT, Arrays.asList(REGENERATION, SHIELD, SLOW,HIGH_MOBILITY, STUN)),
	ARGUS(SOLDIER, Arrays.asList(INVULNERABILITY, DASH)),
	ATLAS(TANK, Arrays.asList(ENDURANCE, CONTROL_IMMUNITY, HIGH_MOBILITY, SKILL_SUPPRESSION)),
	AULUS(SOLDIER, Arrays.asList(HIGH_MOBILITY, REGENERATION, SPLASH_DAMAGE)),
	AURORA(MAGE, Arrays.asList(SLOW, EXPLOSION, SPLASH_DAMAGE, STUN)),
	BADANG(SOLDIER, Arrays.asList(SPLASH_DAMAGE, ENCAGE, SKILL_SUPPRESSION)),
	BALMOND(SOLDIER, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE,REGENERATION, SPLASH_DAMAGE, DASH)),
	BANE(JUNGLE, Arrays.asList(REGENERATION,SLOW, SPLASH_DAMAGE, KNOCK_BACK)),
	BARATS(TANK, Arrays.asList(ENDURANCE, ENCAGE, SKILL_SUPPRESSION ,SLOW, SPLASH_DAMAGE)),
	BAXIA(SOLDIER, Arrays.asList(DASH, REGENERATION_REDUCTION, SPLASH_DAMAGE, SLOW)),
	BEATRIX(DAMAGE, Arrays.asList(LONG_RANGE, SPLASH_DAMAGE, DASH)),
	BELERICK(TANK, Arrays.asList(REFLECTION, HP_POOL, REGENERATION, SKILL_SUPPRESSION)),
	BENEDETA(JUNGLE, Arrays.asList(DASH, INVULNERABILITY, SPLASH_DAMAGE, SLOW, CONTROL_IMMUNITY)),
	BRODY(DAMAGE, Arrays.asList(LONG_RANGE, SLOW, SKILL_SUPPRESSION, HIGH_MOBILITY)),
	BRUNO(DAMAGE, Arrays.asList(REAP, KNOCK_BACK)),
	CARMILLA(TANK, Arrays.asList(ENDURANCE, SLOW)),
	CECILION(MAGE, Arrays.asList(SLOW)),
	CHANGE(MAGE, Arrays.asList(LONG_RANGE, SLOW, SPLASH_DAMAGE, HIGH_MOBILITY)),
	CHOU(DAMAGE, Arrays.asList(CONTROL_IMMUNITY, DASH, SLOW, SHIELD)),
	CLAUDE(DAMAGE, Arrays.asList(HIGH_MOBILITY, REAP)),
	CLINT(JUNGLE, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE,SPLASH_DAMAGE, SKILL_SUPPRESSION)),
	CYCLOPS(MAGE, Arrays.asList(SLOW, HIGH_MOBILITY,ENCAGE)),
	DIGGIE(SUPPORT, Arrays.asList(CONTROL_IMMUNITY, ENCAGE, LONG_RANGE)),
	DYRROTH(DAMAGE, Arrays.asList(REGENERATION, EXPLOSION)),
	EDITH(SOLDIER,Arrays.asList(ENDURANCE, SLOW)),
	ESMERALDA(JUNGLE, Arrays.asList(SHIELD_STEALING, REGENERATION, SPLASH_DAMAGE)),
	ESTES(SUPPORT, Arrays.asList(REGENERATION, SLOW)),
	EUDORA(MAGE, Arrays.asList(STUN, EXPLOSION, SPLASH_DAMAGE)),
	FANNY(DAMAGE, Arrays.asList(HIGH_MOBILITY, REGENERATION)),
	FARAMIS(SUPPORT, Arrays.asList(RESSURRECTION, SPLASH_DAMAGE)),
	FREDERIN(TANK, Arrays.asList(REGENERATION, ENDURANCE, SLOW, REFLECTION)),
	FLORYN(SUPPORT, Arrays.asList(SHIELD, SKILL_SUPPRESSION, SLOW)),
	FRANCO(TANK, Arrays.asList(STUN, REGENERATION, PULL)),
	FREYA(SOLDIER, Arrays.asList(SHIELD, SKILL_SUPPRESSION, REAP)),
	GATOTKACA(TANK, Arrays.asList(ENDURANCE, LONG_RANGE, SPLASH_DAMAGE)),
	GLOO(TANK, Arrays.asList(SLOW, REGENERATION, SKILL_SUPPRESSION, SPLASH_DAMAGE)),
	GORD(MAGE, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE,STUN)),
	GRANGER(DAMAGE, Arrays.asList(HIGH_MOBILITY)),
	GROCK(TANK, Arrays.asList(CONTROL_IMMUNITY, ENCAGE, ENDURANCE)),
	GUINEVERE(JUNGLE, Arrays.asList(SKILL_SUPPRESSION, DASH, REGENERATION)),
	GUSION(JUNGLE, Arrays.asList(HIGH_MOBILITY, EXPLOSION)),
	HANABI(DAMAGE, Arrays.asList(SPLASH_DAMAGE, CONTROL_IMMUNITY, SHIELD, SKILL_SUPPRESSION)),
	HANZO(JUNGLE, Arrays.asList(HIGH_MOBILITY, INVULNERABILITY, INVULNERABILITY)),
	HARITH(MAGE, Arrays.asList(SLOW, HIGH_MOBILITY)),
	HARLEY(JUNGLE, Arrays.asList(DASH, EXPLOSION, SPLASH_DAMAGE)),
	HAYABUSA(DAMAGE, Arrays.asList(DASH, INVULNERABILITY, SPLASH_DAMAGE, REGENERATION, SLOW)),
	HELCURT(JUNGLE, Arrays.asList(SKILL_SUPPRESSION, EXPLOSION, DASH)),
	HILDA(SOLDIER, Arrays.asList(SHIELD, REGENERATION, EXPLOSION, HIGH_MOBILITY)),
	HYLOS(SUPPORT, Arrays.asList(HP_POOL, SLOW, SPLASH_DAMAGE, REGENERATION, STUN)),
	IRITHEL(DAMAGE, Arrays.asList(REAP, SPLASH_DAMAGE, ARMOR_BREAKER_REAL_DAMAGE, SLOW)),
	JAWHEAD(SOLDIER, Arrays.asList(ENDURANCE, SHIELD, HIGH_MOBILITY)),
	JOHNSON(TANK, Arrays.asList(HIGH_MOBILITY, SLOW, STUN, SPLASH_DAMAGE)),
	KADITA(MAGE, Arrays.asList(INVULNERABILITY, EXPLOSION)),
	KAGURA(MAGE, Arrays.asList(CONTROL_IMMUNITY, SPLASH_DAMAGE, SLOW, STUN, SHIELD)),
	KAJA(MAGE, Arrays.asList(REGENERATION, SPLASH_DAMAGE, SKILL_SUPPRESSION, DASH, SLOW)),
	KARINA(JUNGLE, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE, REFLECTION, INVULNERABILITY, DASH, EXPLOSION)),
	KARRIE(DAMAGE, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE, HP_BASED_DAMAGE, REAP, SLOW)),
	KHALEED(SOLDIER, Arrays.asList(ENDURANCE, REGENERATION)),
	KHUFRA(JUNGLE, Arrays.asList(HIGH_MOBILITY, DASH_SUPPRESSION)),
	KIMMY(JUNGLE, Arrays.asList(HIGH_MOBILITY, REAP, LONG_RANGE)),
	JULIAN(JUNGLE, Arrays.asList(REGENERATION, EXPLOSION)),
	LANCELOT(DAMAGE, Arrays.asList(INVULNERABILITY, DASH, SPLASH_DAMAGE)),
	LAPULAPU(TANK, Arrays.asList(SHIELD, SPLASH_DAMAGE, ENDURANCE, CONTROL_IMMUNITY, DASH, REGENERATION)),
	LAYLA(DAMAGE, Arrays.asList(LONG_RANGE, SPLASH_DAMAGE, SLOW)),
	LEOMORD(DAMAGE, Arrays.asList(REGENERATION, ENDURANCE)),
	LESLEY(DAMAGE, Arrays.asList(LONG_RANGE,HIGH_MOBILITY,KNOCK_BACK, INVISIBILITY)),
	LING(DAMAGE, Arrays.asList(INVISIBILITY, HIGH_MOBILITY)),
	LOLITA(SUPPORT, Arrays.asList(DASH, SHIELD, SLOW)),
	LUNOX(MAGE, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE, REAP, CONTROL_IMMUNITY, INVULNERABILITY, SPLASH_DAMAGE)),
	LOUYI(SUPPORT, Arrays.asList(SLOW, SPLASH_DAMAGE,HIGH_MOBILITY, KNOCK_BACK, SHIELD)),
	LYLIA(MAGE, Arrays.asList(SLOW, REGENERATION)),
	MARTIS(SOLDIER, Arrays.asList(CONTROL_IMMUNITY, REGENERATION)),
	MASHA(DAMAGE, Arrays.asList(HIGH_MOBILITY, SHIELD)),
	MATHILDA(SUPPORT, Arrays.asList(HIGH_MOBILITY, DASH, KNOCK_BACK)),
	MELISSA(JUNGLE, Arrays.asList(SLOW, CONTROL_IMMUNITY)),
	MINOTAUR(SUPPORT, Arrays.asList(REGENERATION, STUN, SLOW)),
	MINSITTHAR(SUPPORT, Arrays.asList(DASH_SUPPRESSION,SHIELD, STUN, PULL)),
	MYA(DAMAGE, Arrays.asList(REAP, CONTROL_IMMUNITY, STUN)),
	MOSKOV(DAMAGE, Arrays.asList(REAP, SLOW)),
	NANA(MAGE, Arrays.asList(RESSURRECTION, SLOW, SKILL_SUPPRESSION, SPLASH_DAMAGE)),
	NATALIA(DAMAGE, Arrays.asList(HIGH_MOBILITY, INVISIBILITY, SKILL_SUPPRESSION)),
	NATAN(JUNGLE, Arrays.asList(KNOCK_BACK, LONG_RANGE, SPLASH_DAMAGE, KNOCK_BACK, ARMOR_BREAKER_REAL_DAMAGE, SUMMON)),
	ODETTE(MAGE, Arrays.asList(SPLASH_DAMAGE, STUN,SLOW)),
	PAQUITO(SOLDIER, Arrays.asList(CONTROL_IMMUNITY, SHIELD, KNOCK_BACK, DASH, SKILL_SUPPRESSION)),
	PHARSA(MAGE, Arrays.asList(HIGH_MOBILITY, LONG_RANGE)),
	PHOVEUS(SOLDIER, Arrays.asList(SKILL_SUPPRESSION, DASH, SPLASH_DAMAGE)),
	POPOL(SOLDIER, Arrays.asList(SUMMON, SKILL_SUPPRESSION, REAP)),
	RAFAELA(SUPPORT, Arrays.asList(REGENERATION, SLOW)),
	ROGER(SOLDIER, Arrays.asList(HIGH_MOBILITY, REAP, REGENERATION)),
	RUBY(TANK, Arrays.asList(REGENERATION, SLOW, SPLASH_DAMAGE)),
	SABER(JUNGLE, Arrays.asList(EXPLOSION, SKILL_SUPPRESSION, DASH, SPLASH_DAMAGE)),
	SELENA(MAGE, Arrays.asList(LONG_RANGE, SLOW, STUN)),
	SILVANNA(JUNGLE, Arrays.asList(SHIELD, ENCAGE, SLOW, STUN, DASH)),
	SUN(SOLDIER, Arrays.asList(SUMMON, REAP)),
	TERIZLA(SOLDIER, Arrays.asList(REGENERATION)),
	THAMUZ(SOLDIER, Arrays.asList(REGENERATION, ARMOR_BREAKER_REAL_DAMAGE)),
	TIGREAL(TANK, Arrays.asList(ENDURANCE, KNOCK_BACK, SLOW, SKILL_SUPPRESSION, SPLASH_DAMAGE)),
	URANUS(TANK, Arrays.asList(REGENERATION, SHIELD)),
	VALE(MAGE, Arrays.asList(HIGH_MOBILITY, SLOW, STUN, SPLASH_DAMAGE)),
	VALIR(MAGE, Arrays.asList(SLOW, SKILL_SUPPRESSION, KNOCK_BACK)),
	VALENTINA(MAGE, Arrays.asList(LONG_RANGE,SLOW)),
	VEXANA(MAGE, Arrays.asList(SUMMON, SLOW, SKILL_SUPPRESSION, SPLASH_DAMAGE)),
	WANWAN(DAMAGE, Arrays.asList(CONTROL_IMMUNITY, INVULNERABILITY, STUN, REAP)),
	XAVIER(SUPPORT, Arrays.asList(LONG_RANGE, SPLASH_DAMAGE, SLOW, SKILL_SUPPRESSION)),
	XBORG(SOLDIER, Arrays.asList(ARMOR_BREAKER_REAL_DAMAGE, SHIELD)),
	YISUNSHIN(DAMAGE, Arrays.asList(LONG_RANGE, INVULNERABILITY)),
	YUZHONG(SOLDIER, Arrays.asList(REGENERATION, HIGH_MOBILITY)),
	YVE(MAGE, Arrays.asList(LONG_RANGE, SHIELD, ENCAGE, HIGH_MOBILITY, SPLASH_DAMAGE, CONTROL_IMMUNITY, ENCAGE)),
	ZHASK(SOLDIER, Arrays.asList(SUMMON, SLOW)),
	ZILONG(DAMAGE, Arrays.asList(HIGH_MOBILITY, REAP, CONTROL_IMMUNITY));

	private Role role;
	private List<Behaviour> strengths;
	private Set<Behaviour> weaknesses = new HashSet<Behaviour>();

	Hero(Role role, List<Behaviour> strengths) {
		this.role = role;
		this.strengths = strengths;
	}

	private static Map<String, Hero> heroesNameMap = new HashMap<String, Hero>();

	static {
		Hero[] values = Hero.values();
		int ammountValues = values.length;

		if (heroesNameMap.isEmpty()) {
			for (int i = 0; i < ammountValues; i++) {
				heroesNameMap.put(String.valueOf(values[i]), values[i]);
			}
		}

	}

	public static Map<String, Hero> getHeroesNameMap() {
		return heroesNameMap;
	}

	public Role getRole() {
		return role;
	}

	public Set<Behaviour> getWeaknesses() {
		return weaknesses;
	}

	public List<Behaviour> getStrengths() {
		return strengths;
	}

}