package com.Bean;

public enum Equipment {

	RADIANTARMOR, TWILIGHTARMOR, BRUTEFORCE, IMMORTALITY, DOMINANCEICE, ATHENASSHIELD, ORACLE, ANTIQUECUIRASS,
	GUARDIANHELMET, CURSEDHELMET, THUNDERBELT, QUEENSWINGS, BLADEARMOR

}
